### PR TITLE
Add dismissing_pr_reviews.md

### PR DESCRIPTION
**Pull request by bojanpotocnik**

### CODE REVIEW

**Comment by bojanpotocnik** [comment]
**Merging is blocked** because **Review required**, as set in the _Branch protection rules_.

**Review by RenePotocnik — DISMISSED** [review]
Looks good.

Based on the _Branch protection rules_, this review shall be dismissed if anything is (force) pushed to this repository.

**Comment by bojanpotocnik** [comment]
Force pushed to rebase on `main`. **Review required** again because of the push to this PR and **Dismiss stale pull request approvals when new commits are pushed** branch protection rule enabled.

**Review by RenePotocnik — APPROVED** [review]
I believe this could get annoying if `main` changes frequently and you want to keep this PR updated from the command line, to keep GPG commit verification.

**Comment by bojanpotocnik** [comment]
@RenePotocnik true, however code reviews are important and needs to be invalidated when new code is pushed - also for security reasons (preventing push of malicious code), among others.

It is also true, however, that review should not be invalidated if there were no changes to commits in this PR whatsoever - e.g. if the latest push was pure rebase on the base branch.

**Pull request merged**
