### PR TITLE
Test not-dismissing reviews for pure PR base-branch rebases

### PR DESCRIPTION
**Pull request by bojanpotocnik**

### CODE REVIEW

**Comment by bojanpotocnik** [comment]
`pr-push-rebase-check.yml` was not executed because this PR was opened, not `synchronize`d.

**Comment by bojanpotocnik** [comment]
CI was executed, resulting in _No approved reviews to dismiss, skipping checks_, as expected.
image

**Review by RenePotocnik — DISMISSED** [review]
Not a fan of meaningless changes, but not my monkeys, not my circus.

**Comment by bojanpotocnik** [comment]
I could merge this now, but let me merge something on base branch first, to test CI.

**Comment by RenePotocnik** [comment]
I see you granted yourself privileges and pushed directly to `main`
image

**Rebase and merge** button is still enabled because there are no merge conflicts, but you should avoid pressing it and rebase locally instead - to keep the commit GPG signature.
Force push is required afterwards, and we shall see if this integration is working :thinking:

**Comment by bojanpotocnik** [comment]
1. **Rebase and merge** button was disabled while the integration was running. :heavy_check_mark: 

2. **CI / Check if recent push is only a rebase on the base branch (pull_request)** completed with
    > Keeping the reviews because the latest push was only a rebase on main
    
    and the reviews were not dismissed. :heavy_check_mark: 
    
Now I will change commit message of `Add change 1` commit in this PR and force push again - I am not sure if commit messages are in the patch files :thinking:

**Comment by RenePotocnik** [comment]
Congrats!

Even though pressing the _Compare_ button for the latest force push does not show anything (it does not compare git messages)
image

the change if commit message as properly detected by the CI script and review was invalidated:

image

You've earned yourself a PR approval :medal_sports:

**Review by RenePotocnik — APPROVED** [review]

**Comment by RenePotocnik** [comment]
Even after 19 days,
> Patch length: before = 1733, after = 1733
> Keeping the reviews because the latest push was only a rebase on main

**Pull request closed without merging**
