### PR TITLE
Huge pull-request test

### PR DESCRIPTION
**Pull request by bojanpotocnik**

### CODE REVIEW

**Comment by RenePotocnik** [comment]
What's the estimated time for me to review this, _in years_?

Note that Files changed says ∞.

**Review by RenePotocnik — DISMISSED** [review]
> GitHub: Sorry, this diff is taking too long to generate.

This cannot be said for my review, though.

Comparing the MD5 sums of all sorted files with the content of https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/, it seems that you really just copied the code.
_Such authorship. Much innovation. ~Doge_

**Comment by bojanpotocnik** [comment]
Cannot merge because of **Required statuses must pass before merging**, because **Check if recent push is only a rebase on the base branch** is required. 
However, that check is only executed on `synchronize`, not `opened` https://github.com/bojanpotocnik/github-workflow-playground/blob/15a68cf1341083533a2629eedf9f1afaf605b6f6/.github/workflows/pr-push-rebase-check.yml#L5

**Comment by bojanpotocnik** [comment]
I have removed the above mentioned check from _Status checks that are required._ under **Require status checks to pass before merging** branch protection rule, and the _Rebase and merge_ button is now green.
Doing some rebase, to check whether button is disabled during CI with that option removed.

**Comment by RenePotocnik** [comment]
Despite the fact that this was the expected behavior, it's nice to see that the CI script actually handled its own failure (JavaScript is not your preferred/usual method of psychological torture after all) :clap: 
image

**Comment by bojanpotocnik** [comment]
Based on https://docs.github.com/en/rest/guides/traversing-with-pagination I think that the `application/vnd.github.v3.patch` media type does not support pagination, so either the whole patch will be returned or error _The patch could not be processed because too many files changed_, as it was above.

I will try to produce different patch sizes - trying to find out what is the maximum size returned, and whether this can be more than the JS variable can allocate.

**Review by RenePotocnik — DISMISSED** [review]

**Review by RenePotocnik — DISMISSED** [review]

**Review by RenePotocnik — DISMISSED** [review]

**Review by RenePotocnik — DISMISSED** [review]

**Review by RenePotocnik — APPROVED** [review]

**Pull request closed without merging**
