### PR TITLE
Increasingly large PR test

### PR DESCRIPTION
**Pull request by bojanpotocnik**
While https://github.com/bojanpotocnik/github-workflow-playground/pull/5 tested what happens when the patch file is too large by far, this PR aim to check what exactly is that limit and if patches can be safely retrieved and compared up to that limit.

Note that while opening the PR, GitHub displayed this message:
image

### CODE REVIEW

**Review by RenePotocnik — DISMISSED** [review]

**Comment by bojanpotocnik** [comment]
Patch length: before = 112279963, after = 112279963
Keeping the reviews because the latest push was only a rebase on main

**Review by RenePotocnik — DISMISSED** [review]

**Review by RenePotocnik — DISMISSED** [review]

**Review by RenePotocnik — DISMISSED** [review]

**Review by RenePotocnik — DISMISSED** [review]

**Review by RenePotocnik — DISMISSED** [review]

**Review by RenePotocnik — DISMISSED** [review]

**Review by RenePotocnik — DISMISSED** [review]

**Comment by bojanpotocnik** [comment]
Use these URLs for manual investigation (append '.patch' to download raw patch files):
    Before: https://github.com/bojanpotocnik/github-workflow-playground/compare/main...f3bf9340a76d081a72b36f956ac4be786e500c01
    After:  https://github.com/bojanpotocnik/github-workflow-playground/compare/main...7b90ab0d441cdf44e4499434d1235070ebb8dda5

Patch length: before = 124933653, after = 124930771
Dismissing reviews 1027445276
Dismissing review 1027445276

**Review by RenePotocnik — DISMISSED** [review]

**Comment by bojanpotocnik** [comment]
Patch length: before = 124930771, after = 124950737

**Review by RenePotocnik — DISMISSED** [review]

**Comment by bojanpotocnik** [comment]
Patch length: before = 124950737, after = 125003483

**Review by RenePotocnik — DISMISSED** [review]

**Review by RenePotocnik — DISMISSED** [review]

**Comment by bojanpotocnik** [comment]
Patch length: before = 125087585, after = 125135043

**Comment by bojanpotocnik** [comment]
So, #5 and #6 show that there are 3 cases:
1. Patch is short enough for comparison to succeed
2. Patch is very huge but still shorter than the hard limit - either API request or allocation fails, resulting in _Server Error_.
We are talking about more than 4 million changes, 16000 files and 125 million characters.
4. Patch is larger than the hard limit and API results in _The patch could not be processed because too many files changed_.

**Review by RenePotocnik — DISMISSED** [review]

**Review by RenePotocnik — APPROVED** [review]

**Review by RenePotocnik — APPROVED** [review]

**Pull request closed without merging**
